# Generated by Django 4.1.6 on 2023-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not selected', 'Not selected')], default='Not selected', max_length=25),
        ),
    ]
