# Generated by Django 4.1.6 on 2023-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadesapp', '0002_gamerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
