# Generated by Django 4.1.6 on 2023-02-27 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadesapp', '0003_customuser_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
