# Generated by Django 4.1.6 on 2023-03-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadesapp', '0004_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
