# Generated by Django 4.1.6 on 2023-04-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadesapp', '0009_articlerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='game',
        ),
        migrations.AddField(
            model_name='article',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='hadesapp.game'),
        ),
    ]
