# Generated by Django 4.1.6 on 2023-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadesapp', '0010_remove_article_game_article_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='articles', to='hadesapp.game'),
        ),
    ]
